//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traveldirectWebForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traveldirectWebForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html style=
        ///&quot;margin: 0;padding: 0;font-size: 13px;font-family: &apos;Lato&apos;, sans-serif;line-height: 1.65;&quot;&gt;
        ///
        ///&lt;head style=
        ///&quot;margin: 0;padding: 0;font-size: 13px;font-family: &apos;Lato&apos;, sans-serif;line-height: 1.65;&quot;&gt;
        ///&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; style=
        ///&quot;margin: 0;padding: 0;font-size: 13px;font-family: &apos;Lato&apos;, sans-serif;line-height: 1.65;&quot;&gt;
        ///    &lt;meta content=&quot;width=device-width&quot; name=&quot;viewport&quot; style=
        ///    &quot;margin: 0;padding: 0;font-size: 13px;font-family: &apos;Lat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string thanks_for_contacting {
            get {
                return ResourceManager.GetString("thanks_for_contacting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html style=
        ///&quot;margin: 0;padding: 0;font-size: 13px;font-family: &apos;Lato&apos;, sans-serif;line-height: 1.65;&quot;&gt;
        ///
        ///&lt;head style=
        ///&quot;margin: 0;padding: 0;font-size: 13px;font-family: &apos;Lato&apos;, sans-serif;line-height: 1.65;&quot;&gt;
        ///&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; style=
        ///&quot;margin: 0;padding: 0;font-size: 13px;font-family: &apos;Lato&apos;, sans-serif;line-height: 1.65;&quot;&gt;
        ///    &lt;meta content=&quot;width=device-width&quot; name=&quot;viewport&quot; style=
        ///    &quot;margin: 0;padding: 0;font-size: 13px;font-fa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string thanks_for_subscribing {
            get {
                return ResourceManager.GetString("thanks_for_subscribing", resourceCulture);
            }
        }
    }
}
